name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Create S3 bucket if not exists
      run: |
        aws s3api head-bucket --bucket rps-api-deployment-bucket || aws s3 mb s3://rps-api-deployment-bucket --region us-east-2
      
    - name: Deploy to Lambda
      run: |
        cd src/rps-api
        dotnet lambda deploy-serverless --s3-bucket rps-api-deployment-bucket --stack-name rps-api-stack --force-upload --disable-version-check --capabilities CAPABILITY_IAM
      continue-on-error: true
      
    - name: Check deployment status
      if: ${{ failure() }}
      run: |
        echo "Deployment failed. Checking CloudFormation events..."
        aws cloudformation describe-stack-events --stack-name rps-api-stack --query 'StackEvents[?ResourceStatus==`CREATE_FAILED`].[LogicalResourceId,ResourceStatusReason]' --output table
        exit 1